### ISSUE TITLE
IPPF Investigation

### ISSUE THREAD

**Issue by llamzonc** [hcastro1989/Cognitive-Delivery#16]
- Can we pull L1 data from the IPPF dashboard?

- Can we pull indivual project data (there might be a "Transaction details" in IPPF on the reports tab)

**Comment by llamzonc** [comment]
Could you set up time with Al's contact to walk through the tool on Monday?

**Comment by hcastro1989** [comment]
-contacted Al 1.13.16 for contact information

**Comment by hcastro1989** [comment]
-walk through scheduled for Jan 17th
