### ISSUE TITLE
Investigate Contracts Cube Plan Data 

### ISSUE THREAD

**Issue by hcastro1989** [hcastro1989/Cognitive-Delivery#24]
Contract has different plan data, example CFTYQFF

**Comment by hcastro1989** [comment]
![capture](https://cloud.githubusercontent.com/assets/23216193/21998431/c2e1f300-dc02-11e6-96fb-78055cce84e0.PNG)

**Comment by hcastro1989** [comment]
Plan GP should be the sum of all unique wbsID plans. in contracts cube, plan GP is still divided into wbsID numbers.

**Comment by areyes13** [comment]
collapsed cube without splitting by customer id is up on box
