### ISSUE TITLE
Find Field that Identifies a Contract as T&M or Fixed Cost

### ISSUE THREAD

**Issue by llamzonc** [hcastro1989/Cognitive-Delivery#25]
We need to know if a contract is billed as  Time and Materials or Fixed Cost. We need to know if this field what field identifies this, and if it exists at the L1 level, L2 level or both. 

We may need to ask Al or Bill if we can't find it in the data.

**Comment by hcastro1989** [comment]
Al: re:  Contract type ---- this information is reported 1:1 based on L2 .....and it is found as part of Service type column. I believe this same column will display NA on the L1 reports as there could be many to one relationships (Many L2 to L1)
